language: node_js
node_js:
  - "9"

cache: yarn

branches:
  only:
    - master

before_deploy:
  - yarn build

deploy:
  provider: script
  script:
    - echo "${KEY}" > ${KEYFILE}
    - scp -r -i ${KEYFILE} ${DIR_LOCAL}/* ${USER}@${HOST}:${DIR_REMOTE}
  skip_cleanup: true
  on:
    branch: master
