version: 2

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: prettier
          command: |
            yarn prettier --check
      - run:
          name: lint
          command: |
            yarn lint
      - run:
          name: typecheck
          command: |
            yarn typecheck
      - run:
          name: test
          command: |
            yarn test
