version: 2

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: install lftp
          command: |
            apt-get update -q
            apt-get install -y lftp
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: |
            yarn lint
      - run:
          name: test
          command: |
            yarn test
      - run:
          name: build
          command: |
            yarn build
      - run:
          name: deploy using lftp
          command: |
            lftp -e "set ssl:verify-certificate no; set mirror:set-permissions no; mirror -R ${DIR_LOCAL} ${DIR_REMOTE}; quit" -u ${FTP_USERNAME},${FTP_PASSWORD} ${FTP_HOST}
      - run:
          name: purge cloudflare cache
          command: |
            yarn cloudflare

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
