version: 2

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: |
            yarn lint
      - run:
          name: test
          command: |
            yarn test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build image
          command: |
            docker build -t hackaburg/website .
      - run:
          name: push image to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push hackaburg/website
      - run:
          name: purge cloudflare cache
          command: |
            ./scripts/purge-cloudflare-cache.sh

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
