name: Tests and push apps

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: npm run check

      - name: Check code linting
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [style]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            hackaburg/website:latest
